# fly.toml app configuration file generated for personal-bot-sxidla on 2026-08-24T06:34:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-bot-sxidla'
primary_region = 'ams'

[build]

[[mounts]]
  source = 'data'
  destination = '/app/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
